donga-it-club/past-foward-backend

- .github/ISSUE_TEMPLATE/issue_template.md
- 이슈 템플릿이 정상적으로 불러오지 않기에 누락된 형식을 추가합니다.
- yaml 포맷 추가
> docs: 누락된 yaml 양식을 추가합니다.

- docker-compose.yaml
> feat/#9-add docker-compose

- src/main/java/aws/retrospective/service/RetrospectiveService.java
- 반환 시 nullPointerException이 발생할 수 있는 부분을 수정합니다.
- teamId가 없을 시 null 할당
> fix: teamId가 없을 시 null을 할당합니다.

- src/main/java/aws/retrospective/common/ApiResponse.java
- src/main/java/aws/retrospective/exception/ErrorCode.java
- src/main/java/aws/retrospective/exception/ErrorResponse.java
- src/main/java/aws/retrospective/exception/GlobalExceptionHandler.java
프론트엔드로 구조화된 응답 값 전달
구조화 된 클래스(응답, 예외) API 생성
> feat: 공통 응답 API 추가

- src/main/java/aws/retrospective/controller/SectionController.java
- src/main/java/aws/retrospective/service/SectionService.java
- src/test/java/aws/retrospective/service/SectionServiceTest.java
> feat/#43 fix-create-section-api

- src/main/java/aws/retrospective/controller/RetrospectiveController.java
- src/main/java/aws/retrospective/controller/RetrospectiveTemplateController.java
#40 
- 기존 API에 반영되지 않은 공통 반환 포맷을 적용합니다.
- 로컬 테스트
> chore: 공통 반환 포맷을 적용합니다.

- src/main/java/aws/retrospective/dto/GetRetrospectivesDto.java
- src/main/java/aws/retrospective/dto/RetrospectivesOrderType.java
- src/main/java/aws/retrospective/service/RetrospectiveService.java
- src/test/java/aws/retrospective/service/RetrospectiveServiceTest.java
- #49 
- NEWEST
- OLDEST
- 위와 같이 enum 필드값을 수정합니다.
> fix: RetrospectivesOrderType 필드 수정

- src/main/java/aws/retrospective/controller/RetrospectiveController.java
- src/main/java/aws/retrospective/entity/Retrospective.java
- src/main/java/aws/retrospective/service/RetrospectiveService.java
- src/main/resources/application.yml
- src/test/java/aws/retrospective/service/RetrospectiveServiceTest.java
- src/test/java/aws/retrospective/util/TestUtil.java
- #42 
- 회고 삭제 기능 추가
- soft_delete
> feat: 회고 삭제 API 추가

- src/main/java/aws/retrospective/service/SectionService.java
> fix: 잘못된 엔티티 참조 수정

- src/main/java/aws/retrospective/controller/SectionController.java
- src/main/java/aws/retrospective/dto/CreateSectionDto.java
- src/main/java/aws/retrospective/dto/CreateSectionResponseDto.java
- src/main/java/aws/retrospective/dto/EditSectionRequestDto.java
- src/main/java/aws/retrospective/dto/EditSectionResponseDto.java
- src/main/java/aws/retrospective/dto/IncreaseSectionLikesRequestDto.java
- src/main/java/aws/retrospective/dto/IncreaseSectionLikesResponseDto.java
> feat: API 문서화 추가

- src/main/java/aws/retrospective/common/CommonApiResponse.java
- src/main/java/aws/retrospective/controller/RetrospectiveController.java
- src/main/java/aws/retrospective/controller/RetrospectiveTemplateController.java
- src/main/java/aws/retrospective/controller/SectionController.java
#58 
공통 응답 클래스 ApiResponse -> CommonApiResponse 수정
> feat: 공통 응답 클래스명 수정

- src/main/java/aws/retrospective/controller/RetrospectiveController.java
- 기존 공통 응답 포맷 네이밍 수정에 따른 핫픽스
- ApiResponse TO CommonApiResponse
> fix: 잘못된 리턴타입을 수정합니다.

- src/main/java/aws/retrospective/controller/SectionController.java
#64 
@ApiResponse의 패키지를 static 처리합니다.
> refactor: static import 추가

- .github/workflows/ci.yml
> feat: ci 구축

- src/main/java/aws/retrospective/controller/SectionController.java
- src/main/java/aws/retrospective/dto/DeleteSectionRequestDto.java
- src/main/java/aws/retrospective/service/SectionService.java
- src/test/java/aws/retrospective/service/SectionServiceTest.java
#78 
- 요청 dto 생성
- validation 사용
- 서비스 레이어 예외 검증 로직 추가
> feat: 예외 검증 로직 추가

- build.gradle
- src/main/resources/application.yml
> feat: health check API 추가

- src/main/java/aws/retrospective/controller/SectionController.java
- src/main/java/aws/retrospective/dto/GetSectionsRequestDto.java
- src/main/java/aws/retrospective/dto/GetSectionsResponseDto.java
> feat: swagger 필드 정보 명세

- src/main/java/aws/retrospective/controller/SectionController.java
- src/main/java/aws/retrospective/dto/CreateSectionDto.java
- src/main/java/aws/retrospective/dto/CreateSectionResponseDto.java
- src/main/java/aws/retrospective/dto/EditSectionRequestDto.java
- src/main/java/aws/retrospective/dto/EditSectionResponseDto.java
- src/main/java/aws/retrospective/dto/FindSectionCountRequestDto.java
- src/main/java/aws/retrospective/dto/FindSectionCountResponseDto.java
- src/main/java/aws/retrospective/dto/GetSectionsRequestDto.java
- src/main/java/aws/retrospective/dto/GetSectionsResponseDto.java
- src/main/java/aws/retrospective/dto/IncreaseSectionLikesResponseDto.java
- src/main/java/aws/retrospective/service/SectionService.java
- #92 
- 명세서 작성이 안된 API -> 명세서 작성
- 기존 swagger -> 명칭 변경
> feat: swagger 명세서 작성

- src/main/java/aws/retrospective/dto/GetPreSignedUrlRequestDto.java
잘못된 validate annotation을 수정합니다.
NotEmpty -> NotNull
> fix: NotEmpty -> NotNull

- src/main/resources-prod/application-prod.yml
s3 bucket 정보를 환경변수로 처리합니다.
- s3 bucket 환경변수화
> fix: bucket을 환경변수화합니다.

- src/main/java/aws/retrospective/dto/RetrospectiveResponseDto.java
#118 
- RetrospectiveResponseDto에 description 필드를 추가합니다.
> feat: add description in RetrospectiveResponseDto

- .github/workflows/cd.yml
- scripts/deploy.sh
- 서버가 이미 띄워져있으면 배포시 에러가 발생하여 이를 해결하기 위함 
- 서버 종료 이후 jar 복사 및 배포하도록 로직 수정
> fix: deploy.sh 수정

- src/main/java/aws/retrospective/controller/SectionController.java
- src/main/java/aws/retrospective/dto/AssignUserRequestDto.java
- src/main/java/aws/retrospective/entity/ActionItem.java
- src/main/java/aws/retrospective/exception/GlobalExceptionHandler.java
- src/main/java/aws/retrospective/repository/ActionItemRepository.java
- src/main/java/aws/retrospective/service/SectionService.java
- src/test/java/aws/retrospective/service/SectionServiceTest.java
- #126 
- Action Items 담당자 지정 API 생성
> feat: 업무 담당자를 지정할 수 있다.

- src/main/java/aws/retrospective/controller/UserController.java
- src/main/java/aws/retrospective/dto/GetUserInfoDto.java
- src/main/java/aws/retrospective/service/UserService.java
> feat: 유저 정보 조회 API 추가

- src/main/java/aws/retrospective/config/SwaggerConfig.java
- src/main/resources-local/application-local.yml
- src/main/resources-prod/application-prod.yml
- swagger url 지정
- 환경변수에 도메인 설정
> feat: apply https swagger in prod

- src/main/java/aws/retrospective/dto/GetTeamUsersResponseDto.java
- src/main/java/aws/retrospective/entity/UserTeam.java
- src/main/java/aws/retrospective/repository/UserTeamRepositoryCustomImpl.java
- src/test/java/aws/retrospective/service/TeamServiceTest.java
> feat: 팀원 조회 응답 필드 추가

- build.gradle
- src/main/java/aws/retrospective/controller/InviteTeamMemberController.java
- src/main/java/aws/retrospective/dto/InviteTeamMemberDTO.java
- src/main/java/aws/retrospective/entity/TeamInvite.java
- src/main/java/aws/retrospective/repository/TeamInvitationRepository.java
- src/main/java/aws/retrospective/service/InviteTeamMemberService.java
- src/main/java/aws/retrospective/service/QRCodeService.java
- src/main/resources/application.yml
- src/test/java/aws/retrospective/service/InviteTeamMemberServiceTest.java
> Feat/#37 팀원 초대 API

- src/main/java/aws/retrospective/service/RetrospectiveService.java
#150 
- hasBookmarksByUser 사용 로직 수정
> fix: hasBookmarksByUser 수정

- src/main/java/aws/retrospective/dto/GetRetrospectiveResponseDto.java
- src/main/java/aws/retrospective/service/RetrospectiveService.java
- src/test/java/aws/retrospective/service/RetrospectiveServiceTest.java
- #148 
응답 데이터로 회고 유형(개인, 팀)를 추가합니다.
> feat: 회고 유형 응답 데이터  추가

- src/main/java/aws/retrospective/dto/GetRetrospectiveResponseDto.java
- src/main/java/aws/retrospective/service/RetrospectiveService.java
- src/test/java/aws/retrospective/service/RetrospectiveServiceTest.java
> feat: 응답 dto 데이터 추가

- src/main/java/aws/retrospective/repository/RetrospectiveRepository.java
- src/main/java/aws/retrospective/service/RetrospectiveService.java
> fix: 개인 회고 조회가 안 되던 오류 수정

- src/main/java/aws/retrospective/controller/SurveyController.java
- src/main/java/aws/retrospective/dto/SurveyDto.java
- #45 
- Survey 저장 API 수정
- surveyId 값을 클라이언트로부터 받지 않고 자동으로 할당되도록 수정
> fix: #45 Survey 저장 API 수정

- src/main/java/aws/retrospective/dto/EmailSenderDto.java
- #160 
- 사용자가 메일을 보낼 시, AWS SES에서 관리자 -> 관리자 로 보내도록 수정
> fix: 메일 전송 오류 수정

- src/main/java/aws/retrospective/dto/GetSectionsRequestDto.java
- src/main/java/aws/retrospective/service/SectionService.java
- src/test/java/aws/retrospective/service/SectionServiceTest.java
- #163 
- 개인 회고가 조회되지 않던 오류 수정
> fix: 개인 회고를 조회할 수 있다

- src/main/java/aws/retrospective/controller/TeamController.java
- src/main/java/aws/retrospective/repository/UserTeamRepositoryCustom.java
- src/main/java/aws/retrospective/repository/UserTeamRepositoryCustomImpl.java
- src/main/java/aws/retrospective/service/InviteTeamMemberService.java
> feat/#138 팀원 삭제 API 추가

- src/main/java/aws/retrospective/controller/TeamController.java
- src/main/java/aws/retrospective/repository/UserTeamRepositoryCustom.java
- src/main/java/aws/retrospective/repository/UserTeamRepositoryCustomImpl.java
- src/main/java/aws/retrospective/service/InviteTeamMemberService.java
Reverts donga-it-club/past-foward-backend#166
> Revert "feat/#138 팀원 삭제 API 추가"

- src/main/java/aws/retrospective/controller/SurveyController.java
- src/main/java/aws/retrospective/dto/SurveyDto.java
- src/main/java/aws/retrospective/entity/Survey.java
- src/main/java/aws/retrospective/service/SurveyService.java
- src/test/java/aws/retrospective/service/SurveyServiceTest.java
> feat: purpose타입을 배열로 받을 수 있도록 합니다.

- src/main/java/aws/retrospective/repository/UserTeamRepository.java
- src/main/java/aws/retrospective/service/InviteTeamMemberService.java
#176 
- 팀 초대 수락 재참여시 바로 return
> feat: 팀 초대 수락 재참여시 바로 return

- src/main/java/aws/retrospective/dto/RetrospectiveResponseDto.java
> feat: 반환 시 작성자 필드를 추가합니다.

- src/main/java/aws/retrospective/controller/UserController.java
- src/main/java/aws/retrospective/dto/UpdateUserProfileRequestDto.java
- src/main/java/aws/retrospective/dto/UpdateUserProfileResponseDto.java
- src/main/java/aws/retrospective/entity/User.java
- src/main/java/aws/retrospective/service/UserService.java
> feat: 유저 정보 수정 API 추가

- src/main/java/aws/retrospective/specification/RetrospectiveSpecification.java
> fix: join문 수정

- src/main/java/aws/retrospective/dto/GetCommentDto.java
- src/main/java/aws/retrospective/dto/GetSectionsResponseDto.java
- src/main/java/aws/retrospective/service/SectionService.java
- #190 
- Section 전체 조회 응답 필드 추가
> feat: section 조회 응답 데이터 추가

- src/main/java/aws/retrospective/entity/Retrospective.java
- src/main/java/aws/retrospective/entity/Section.java
- src/main/java/aws/retrospective/service/SectionService.java
- src/test/java/aws/retrospective/service/SectionServiceTest.java
> refactor: Section 코드 리팩토링

- src/main/java/aws/retrospective/controller/SectionController.java
- src/main/java/aws/retrospective/dto/AssignUserRequestDto.java
- src/main/java/aws/retrospective/entity/ActionItem.java
- src/main/java/aws/retrospective/entity/Section.java
- src/main/java/aws/retrospective/repository/ActionItemRepository.java
- src/main/java/aws/retrospective/repository/SectionRepository.java
- src/main/java/aws/retrospective/service/SectionService.java
- src/test/java/aws/retrospective/service/SectionServiceTest.java
- #194 
- cascade.remove 옵션 추가
- 선택된 담당자가 아닌 로그인한 사용자가 선택되는 문제 수정
> fix: 담당자 지정 문제 수정

- src/main/java/aws/retrospective/dto/GetActionItemsResponseDto.java
- src/main/java/aws/retrospective/dto/GetSectionsResponseDto.java
- src/main/java/aws/retrospective/repository/SectionRepository.java
- src/main/java/aws/retrospective/service/SectionService.java
- #202 
- Section 조회시에 Action Items 같이 응답
> feat: Section 조회시에 Action Items를 조회할 수 있다.

- src/main/java/aws/retrospective/dto/EditSectionRequestDto.java
- src/main/java/aws/retrospective/dto/GetSectionsResponseDto.java
- src/main/java/aws/retrospective/service/SectionService.java
- #206 
- 회고 전체 조회 시에 작성자 id 추가
> feat: 응답 필드 추가

- src/main/java/aws/retrospective/entity/Section.java
- src/main/java/aws/retrospective/service/SectionService.java
- #210 
- Action Item 테이블에만 값이 저장되고, Section 테이블에는 값이 저장되지 않았던 문제 해결
> fix: 담당자 지정 오류 수정

- src/main/java/aws/retrospective/controller/NotificationController.java
- src/main/java/aws/retrospective/dto/GetNotificationResponseDto.java
- src/main/java/aws/retrospective/entity/Notification.java
- #221 
- 알림 받는 사용자의 프로필 이미지 -> 알림을 발생시킨 사용자의 프로필 이미지
> fix: 응답 필드 수정

- src/main/java/aws/retrospective/controller/SectionController.java
- src/main/java/aws/retrospective/dto/AssignKudosResponseDto.java
- src/main/java/aws/retrospective/dto/CreateSectionResponseDto.java
- src/main/java/aws/retrospective/dto/EditSectionResponseDto.java
- src/main/java/aws/retrospective/dto/IncreaseSectionLikesResponseDto.java
- src/main/java/aws/retrospective/entity/Likes.java
- src/main/java/aws/retrospective/entity/Notification.java
- src/main/java/aws/retrospective/entity/Retrospective.java
- src/main/java/aws/retrospective/entity/Section.java
- src/main/java/aws/retrospective/service/CommentService.java
- src/main/java/aws/retrospective/service/SectionService.java
- src/test/java/aws/retrospective/service/NotificationServiceTest.java
- src/test/java/aws/retrospective/service/SectionServiceTest.java
- src/test/java/aws/retrospective/util/TestUtil.java
- src/test/resources/bootstrap-test.yml
- #236 
- 동일한 사용자는 회고 카드에 좋아요를 1번만 누를 수 있도록 제약 조건을 추가합니다.
- 기존 회고 카드(Section) 관련된 API를 리팩토링 합니다.
- 정적 팩토리 메서드 -> 빌더 패턴 
> refactor: Section API 개선

- src/main/java/aws/retrospective/controller/RetrospectiveGroupController.java
- src/main/java/aws/retrospective/dto/CreateRetrospectiveGroupDto.java
- src/main/java/aws/retrospective/dto/CreateRetrospectiveGroupResponseDto.java
- src/main/java/aws/retrospective/dto/GetRetrospectiveGroupResponseDto.java
- src/main/java/aws/retrospective/dto/GetRetrospectiveGroupsDto.java
- src/main/java/aws/retrospective/dto/RetrospectiveGroupResponseDto.java
- src/main/java/aws/retrospective/dto/UpdateRetrospectiveGroupBoardsDto.java
- src/main/java/aws/retrospective/dto/UpdateRetrospectiveGroupDto.java
- src/main/java/aws/retrospective/entity/Bookmark.java
- src/main/java/aws/retrospective/entity/Retrospective.java
- src/main/java/aws/retrospective/entity/RetrospectiveGroup.java
- src/main/java/aws/retrospective/repository/RetrospectiveGroupRepository.java
- src/main/java/aws/retrospective/service/RetrospectiveGroupService.java
- src/main/java/aws/retrospective/specification/RetrospectiveGroupSpecification.java
- src/test/java/aws/retrospective/service/RetrospectiveGroupServiceTest.java
- src/test/java/aws/retrospective/util/TestUtil.java
- #227 
- 회고 그룹 API
- TestUtill에 그룹 추가
- 테스트 코드
- Specification -> querydsl, pageable
> feat: Retrospective Grouping

- src/main/java/aws/retrospective/service/NotificationService.java
- #256 
- 초기 Redis가 비어있을 경우 알림이 조회되지 않는 오류 수정
-> Redis에 아무 데이터가 없는 경우 현재 시간 마지막 알림 시간으로 등록
> fix: 알림 생성 문제 수정

- src/main/java/aws/retrospective/controller/NotificationController.java
- src/main/java/aws/retrospective/controller/SectionController.java
- 무엇을 위한 PR인지, 어떠한 이유로 해당 PR을 열게 되었는지에 대한 개요를 적어주세요!
- 주요 변경사항을 적어주세요!
> chore: user 정보 추가

- src/main/java/aws/retrospective/dto/GetNotificationResponseDto.java
- src/main/java/aws/retrospective/service/NotificationService.java
- #260 
- 응답 데이터를 반환하는 과정에서 직렬화 오류를 수정합니다.
> fix: redis와 java 간의 직렬화 문제 해결

- src/main/java/aws/retrospective/controller/NoticeBoardUserController.java
- src/main/java/aws/retrospective/controller/NoticeBoardWritingAdminController.java
- src/main/java/aws/retrospective/dto/NoticeBoardListDto.java
- src/main/java/aws/retrospective/dto/NoticeBoardWritingResponseDto.java
- src/main/java/aws/retrospective/dto/PagedResponseDto.java
- src/main/java/aws/retrospective/entity/NoticeBoardViewCounting.java
- src/main/java/aws/retrospective/entity/NoticeBoardWriting.java
- src/main/java/aws/retrospective/repository/NoticeBoardViewCountingRepository.java
- src/main/java/aws/retrospective/repository/NoticeBoardWritingRepository.java
- src/main/java/aws/retrospective/service/NoticeBoardWritingService.java
- src/test/java/aws/retrospective/service/NoticeBoardWritingServiceTest.java
> feat: 공지사항/이용약관 게시판 글 조회

- src/test/java/aws/retrospective/service/NoticeBoardWritingServiceTest.java
- 리더 권한 충돌 해결하며, 누락된 서비스 테스트 코드 추가
- 누락된 코드 추가
> Fix: 누락된 NoticeBoardWritingServiceTest 추가

- src/main/java/aws/retrospective/dto/GetActionItemsResponseDto.java
- src/main/java/aws/retrospective/dto/GetCommentDto.java
- src/main/java/aws/retrospective/dto/GetSectionsResponseDto.java
- src/main/java/aws/retrospective/entity/Section.java
- src/main/java/aws/retrospective/repository/SectionRepository.java
- src/main/java/aws/retrospective/repository/SectionRepositoryCustom.java
- src/main/java/aws/retrospective/repository/SectionRepositoryCustomImpl.java
- src/main/java/aws/retrospective/service/SectionService.java
- src/test/java/aws/retrospective/service/SectionServiceTest.java
> feat: 삭제된 코드 추가

- src/main/java/aws/retrospective/controller/RetrospectiveController.java
- 500 에러로 인해 컨트롤러 api 수정
- retrospectiveController api 수정
> fix: RetrospectiveController 수정

- src/main/java/aws/retrospective/repository/SectionRepositoryCustomImpl.java
- #282 
- left join으로 발생하는 중복 데이터를 group by를 사용하여 제거합니다.
> fix: left join 추가

- src/main/java/aws/retrospective/specification/RetrospectiveGroupSpecification.java
> fix: RetrospectiveGroupSpecification.withUserId to correctly filter by userId

- src/main/java/aws/retrospective/controller/RetrospectiveGroupController.java
- src/main/java/aws/retrospective/dto/GetRetrospectiveGroupResponseDto.java
- src/main/java/aws/retrospective/dto/RetrospectiveResponseDto.java
- src/main/java/aws/retrospective/service/RetrospectiveGroupService.java
> feat: 회고 그룹 API 수정

- src/main/java/aws/retrospective/dto/GetUserInfoDto.java
- src/main/java/aws/retrospective/dto/NoticeBoardWritingRequestDto.java
- src/main/java/aws/retrospective/dto/NoticeBoardWritingResponseDto.java
- src/main/java/aws/retrospective/service/NoticeBoardWritingService.java
- src/main/java/aws/retrospective/service/UserService.java
- src/test/java/aws/retrospective/service/NoticeBoardWritingServiceTest.java
- #288 
- request 값으로 status 요소 추가 -> private SaveStatus status;
- response 값으로 isAdministrator 요소 추가
> fix : 게시글 저장/임시저장 api 수정

- src/main/java/aws/retrospective/dto/NoticeBoardListDto.java
- src/main/java/aws/retrospective/dto/NoticeBoardWritingRequestDto.java
- src/main/java/aws/retrospective/dto/NoticeBoardWritingResponseDto.java
- src/main/java/aws/retrospective/entity/NoticeBoardWriting.java
- src/main/java/aws/retrospective/service/NoticeBoardWritingService.java
- src/test/java/aws/retrospective/service/NoticeBoardWritingServiceTest.java
#291 
- 게시글/임시게시글 작성 requestDTO에 thumbnail 추가
- 게시글 listDTO에 thumbnail 추가
> fix : Thumbnail 추가

- src/main/java/aws/retrospective/service/RetrospectiveGroupService.java
> fix#293 기존 회고 제거 서비스 수정

- src/main/java/aws/retrospective/service/SectionService.java
- #295 
-kudos 템플릿에 이미 사용자가 지정되어 있는 상황에서 다른 사용자로 변경할 수 있도록 수정합니다.
> fix: 이미 kudos 템플릿에 칭찬 대상자가 있는 경우 새로운 사용자로 바꿀 수 있도록 수정

- src/main/java/aws/retrospective/repository/SectionRepositoryCustomImpl.java
- src/test/java/aws/retrospective/repository/SectionRepositoryTest.java
- 무엇을 위한 PR인지, 어떠한 이유로 해당 PR을 열게 되었는지에 대한 개요를 적어주세요!
- #308 
- 조회 조건으로 where 절을 추가하여 다른 회고보드에 작성된 회고 카드가 조회되지 않도록 한다.
> fix: where 조건 추가

- build.gradle
- src/main/java/aws/retrospective/RetrospectiveApplication.java
- src/main/java/aws/retrospective/config/JpaConfig.java
- src/main/java/aws/retrospective/controller/SectionController.java
- src/main/java/aws/retrospective/exception/GlobalExceptionHandler.java
- src/test/java/aws/retrospective/controller/SectionControllerTest.java
> feat: 회고카드 등록 Presentation Layer 테스트
